#!/bin/bash
# Verifier for cpp-foxglove-sdk-parameter-handler (Harbor separate verifier, no network).
#
# Harbor uploads the [[artifacts]] directories/files from the agent container to the same paths
# under /workspace/repo in this container, which otherwise holds a pristine tree with a warm build.
# This script:
#   0. restores every path the verifier executes from the pristine copy, drops in the hidden gold
#      tests and the gold param-server example, and runs anti-cheat greps on the submission;
#   1. rebuilds the C library (cargo via corrosion, remote access ON) and the C++ SDK, tests and
#      examples in the warm build directory;
#   2. checks that the submitted cbindgen header equals the one regenerated by the build;
#   3. checks the deprecation contract with compile-only probes;
#   4. runs the hidden Catch2 cases and the full upstream C++ suite (exact counts, one process per
#      case via ctest, as upstream's `make -C cpp test` does);
#   5. runs the C crate's own unit tests;
#   6. compiles the C++ and C parity drivers against the fresh libraries and compares their
#      ws-protocol transcripts with the Rust SDK reference server's;
#   7. writes /logs/verifier/score.json (per-group attribution) and reward.txt (1 iff all pass).
set -uo pipefail

OUT=/logs/verifier
mkdir -p "$OUT"
echo 0 > "$OUT/reward.txt"

REPO=/workspace/repo
PRISTINE=/opt/pristine
TESTS=/tests
REF=/opt/refserver/parity_refserver
PY=python3
JOBS=4

EXPECTED_TOTAL_CASES=76       # 71 upstream Catch2 cases at b2fb3fab (arena 2, channel 11, mcap 20, messages 3,
                              # parameter 7, system_info 4, websocket 24; confirmed by ctest -N) + 5 hidden cases from #1258
EXPECTED_PR_CASES=5
EXPECTED_MIN_C_UNIT_TESTS=18  # #[test] count in c/src at b2fb3fab (gateway.rs excluded: feature-gated)

GROUPS_TSV="$OUT/groups.tsv"
: > "$GROUPS_TSV"
mark() {
  # mark <group> <pass|fail|skip> [detail]
  printf '%s\t%s\t%s\n' "$1" "$2" "${3:-}" >> "$GROUPS_TSV"
  echo "[verifier] $1: $2 ${3:-}"
}

finish() {
  $PY - "$GROUPS_TSV" "$OUT/score.json" "$OUT/reward.txt" <<'PY'
import json, sys
groups = {}
order = []
for line in open(sys.argv[1]):
    line = line.rstrip("\n")
    if not line:
        continue
    name, status, detail = (line.split("\t", 2) + ["", ""])[:3]
    groups[name] = {"status": status, "detail": detail}
    order.append(name)
required = ["anti_cheat", "restore", "build_lib", "build_tests", "build_example", "build_all",
            "header_in_sync", "deprecation_marked", "pr_tests", "regressions", "c_unit_tests",
            "api_validation", "parity_cpp", "parity_c"]
passed = all(groups.get(g, {}).get("status") == "pass" for g in required)
json.dump({"reward": 1 if passed else 0, "required_groups": required,
           "groups": {g: groups[g] for g in order}}, open(sys.argv[2], "w"), indent=1)
open(sys.argv[3], "w").write("1\n" if passed else "0\n")
print("[verifier] reward:", 1 if passed else 0)
PY
  exit 0
}
trap finish EXIT

# ---------------------------------------------------------------------------------------------
# 0. Anti-cheat on the submitted paths, then restore everything else from the pristine tree.
# ---------------------------------------------------------------------------------------------
SUBMITTED=(c/src c/include c/cbindgen.toml c/cbindgen.prelude.toml
           cpp/foxglove/include cpp/foxglove/src cpp/cmake/foxglove-sources.cmake)
ac_problems=""
for p in "${SUBMITTED[@]}"; do
  [ -e "$REPO/$p" ] || ac_problems+="missing:$p "
done
if [ -z "$ac_problems" ]; then
  links=$(cd "$REPO" && find "${SUBMITTED[@]}" -type l 2>/dev/null | head -5)
  [ -n "$links" ] && ac_problems+="symlinks:$(echo "$links" | tr '\n' ',') "
  pattern='/logs/|reward\.txt|score\.json|refserver|run_parity|/tests/|LD_PRELOAD|catch_discover|std::process::Command|popen\(|execv|dlopen\('
  hits=$(cd "$REPO" && grep -rnE "$pattern" "${SUBMITTED[@]}" 2>/dev/null | head -10)
  [ -n "$hits" ] && ac_problems+="grep:$(echo "$hits" | head -3 | tr '\n' ';') "
  # The source list must stay a list of bare filenames under cpp/foxglove/src.
  if grep -nE '(\.\./|^\s*/|\$\{)' "$REPO/cpp/cmake/foxglove-sources.cmake" | grep -vE '^\s*#' | grep -qE '\.(cpp|cc|cxx|c)\b'; then
    ac_problems+="sources-list-path-escape "
  fi
fi
if [ -z "$ac_problems" ]; then mark anti_cheat pass; else mark anti_cheat fail "$ac_problems"; fi

restore_dir() { rsync -a --delete "$PRISTINE/$1/" "$REPO/$1/"; }
restore_file() { mkdir -p "$(dirname "$REPO/$1")" && cp "$PRISTINE/$1" "$REPO/$1"; }
{
  restore_dir rust
  restore_dir python
  restore_dir schemas
  restore_dir cpp/foxglove/tests
  restore_dir cpp/foxglove_data_loader
  restore_dir cpp/examples
  for f in Cargo.toml Cargo.lock clippy.toml rustfmt.toml c/Cargo.toml c/build.rs \
           cpp/CMakeLists.txt cpp/Makefile cpp/sanitize-ignorelist.txt cpp/test_callbacks.cpp; do
    restore_file "$f"
  done
  for f in "$PRISTINE"/cpp/cmake/*; do
    b=$(basename "$f")
    [ "$b" = "foxglove-sources.cmake" ] || cp "$f" "$REPO/cpp/cmake/$b"
  done
  rm -rf "$REPO/.cargo" && cp -a "$PRISTINE/.cargo" "$REPO/.cargo"
  # Hidden gold tests replace the upstream websocket test file; the gold example must compile
  # against the submitted API.
  cp "$TESTS/hidden/test_websocket.cpp" "$REPO/cpp/foxglove/tests/test_websocket.cpp"
  cp "$TESTS/hidden/param-server-main.cpp" "$REPO/cpp/examples/param-server/src/main.cpp"
} && mark restore pass || mark restore fail "restore step failed"

# Keep the submitted header aside: the cargo build regenerates it via c/build.rs.
cp "$REPO/c/include/foxglove-c/foxglove-c.h" "$OUT/submitted-foxglove-c.h" 2>/dev/null || true

# ---------------------------------------------------------------------------------------------
# 1. Clean-room rebuild in the warm build directory (same flags as `make -C cpp build`).
# ---------------------------------------------------------------------------------------------
BUILD="$REPO/cpp/build"
build_ok=1
# shellcheck disable=SC2086
if ! (cd "$REPO/cpp" && timeout 600 cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=true \
        -DFOXGLOVE_REMOTE_ACCESS=ON ${CMAKE_ARGS:-} -B build > "$OUT/cmake-configure.log" 2>&1); then
  mark build_lib fail "cmake configure failed (see cmake-configure.log)"; build_ok=0
elif ! timeout 2400 cmake --build "$BUILD" -j "$JOBS" --target foxglove_cpp_shared > "$OUT/build-lib.log" 2>&1; then
  mark build_lib fail "C library or C++ SDK failed to build (see build-lib.log)"; build_ok=0
else
  mark build_lib pass
fi

if [ "$build_ok" = 1 ]; then
  if timeout 1200 cmake --build "$BUILD" -j "$JOBS" --target tests > "$OUT/build-tests.log" 2>&1; then
    mark build_tests pass
  else
    mark build_tests fail "hidden/upstream Catch2 tests failed to compile (see build-tests.log)"
  fi
  if timeout 600 cmake --build "$BUILD" -j "$JOBS" --target example_param_server > "$OUT/build-example.log" 2>&1; then
    mark build_example pass
  else
    mark build_example fail "gold param-server example failed to compile against the submitted API"
  fi
  if timeout 1200 cmake --build "$BUILD" -j "$JOBS" > "$OUT/build-all.log" 2>&1; then
    mark build_all pass
  else
    mark build_all fail "full cpp build failed (see build-all.log)"
  fi
else
  mark build_tests skip; mark build_example skip; mark build_all skip
fi

# ---------------------------------------------------------------------------------------------
# 2. Generated header in sync with c/src (upstream CI: `git diff --exit-code` after the build).
# ---------------------------------------------------------------------------------------------
if [ "$build_ok" = 1 ]; then
  if [ -f "$OUT/submitted-foxglove-c.h" ] && cmp -s "$OUT/submitted-foxglove-c.h" "$REPO/c/include/foxglove-c/foxglove-c.h"; then
    mark header_in_sync pass
  else
    diff -u "$OUT/submitted-foxglove-c.h" "$REPO/c/include/foxglove-c/foxglove-c.h" > "$OUT/header.diff" 2>&1
    mark header_in_sync fail "submitted foxglove-c.h differs from cbindgen output (see header.diff)"
  fi
else
  mark header_in_sync skip
fi

# ---------------------------------------------------------------------------------------------
# Locate the freshly built libraries for the probes and drivers.
# ---------------------------------------------------------------------------------------------
LIB_CPP=$(find "$BUILD" -maxdepth 1 -name 'libfoxglove_cpp_shared.so*' -print -quit 2>/dev/null)
[ -z "$LIB_CPP" ] && LIB_CPP=$(find "$BUILD" -name 'libfoxglove_cpp_shared.so*' -print -quit 2>/dev/null)
LIB_C=$(find "$BUILD" -maxdepth 1 -name 'libfoxglove.so' -print -quit 2>/dev/null)
[ -z "$LIB_C" ] && LIB_C=$(find "$BUILD" -name 'libfoxglove.so' -path '*release*' -print -quit 2>/dev/null)
LIBDIR_CPP=$(dirname "${LIB_CPP:-/nonexistent/x}")
LIBDIR_C=$(dirname "${LIB_C:-/nonexistent/x}")
INC=(-I"$REPO/cpp/foxglove/include" -I"$REPO/c/include")

# ---------------------------------------------------------------------------------------------
# 3. Deprecation contract (compile-only probes).
# ---------------------------------------------------------------------------------------------
if [ "$build_ok" = 1 ]; then
  PROBE="$TESTS/parity/deprecation_probe.cpp"
  dep_detail=""
  if g++ -std=c++17 -fsyntax-only -Werror=deprecated-declarations -DFOXGLOVE_REMOTE_ACCESS "${INC[@]}" -DPROBE_SERVER "$PROBE" > "$OUT/probe-server.log" 2>&1; then
    dep_detail+="WebSocketServerCallbacks legacy members not deprecated; "
  fi
  if g++ -std=c++17 -fsyntax-only -Werror=deprecated-declarations -DFOXGLOVE_REMOTE_ACCESS "${INC[@]}" -DPROBE_GATEWAY "$PROBE" > "$OUT/probe-gateway.log" 2>&1; then
    dep_detail+="RemoteAccessGatewayCallbacks legacy members not deprecated; "
  fi
  if ! g++ -std=c++17 -fsyntax-only -Werror=deprecated-declarations -DFOXGLOVE_REMOTE_ACCESS "${INC[@]}" -DPROBE_CONTROL "$PROBE" > "$OUT/probe-control.log" 2>&1; then
    dep_detail+="control probe (options move, handler copy) does not compile warning-free (see probe-control.log); "
  fi
  if [ -z "$dep_detail" ]; then mark deprecation_marked pass; else mark deprecation_marked fail "$dep_detail"; fi
else
  mark deprecation_marked skip
fi

# ---------------------------------------------------------------------------------------------
# 4. Catch2: hidden PR cases (exactly 5) and the full suite (exactly 76 cases, none failing).
# Every case runs in its own process through ctest (catch_discover_tests registers one ctest test
# per Catch2 case), exactly as upstream's `make -C cpp test` does. Running the whole binary in one
# process is not equivalent: upstream cases assume fresh process-global state (channel ids start
# at 1, for example), fail when they share a process, and some then hang waiting on callbacks.
# Exact counts are cross-checked from three sources: the binary's --list-tests, ctest -N, and the
# number of test cases ctest actually ran (JUnit); skipped/disabled/not-run cases fail the group.
# ---------------------------------------------------------------------------------------------
TESTBIN="$BUILD/tests"
junit_ok() {
  # junit_ok <xml> -> prints "tests failures errors skipped"; returns 0 iff failures+errors+skipped == 0 and tests > 0
  $PY - "$1" <<'PY'
import sys, xml.etree.ElementTree as ET
try:
    root = ET.parse(sys.argv[1]).getroot()
except Exception as exc:
    print("0 1 1 0 parse-error", exc); sys.exit(1)
suites = [root] if root.tag == "testsuite" else list(root.iter("testsuite"))
t = sum(int(s.get("tests", 0)) for s in suites)
f = sum(int(s.get("failures", 0)) for s in suites)
e = sum(int(s.get("errors", 0)) for s in suites)
k = sum(int(s.get("skipped", 0)) + int(s.get("disabled", 0)) for s in suites)
print(t, f, e, k)
sys.exit(0 if f + e + k == 0 and t > 0 else 1)
PY
}
if [ "$build_ok" = 1 ] && [ -x "$TESTBIN" ]; then
  # Catch2 v3 ends the listing with "N test cases" (unfiltered) or "N matching test cases".
  listed_total=$("$TESTBIN" --list-tests 2>/dev/null | grep -oE '^[0-9]+ (matching )?test cases?' | grep -oE '^[0-9]+')
  listed_pr=$("$TESTBIN" --list-tests "ParameterHandler*" 2>/dev/null | grep -oE '^[0-9]+ (matching )?test cases?' | grep -oE '^[0-9]+')
  ctest_total=$(cd "$BUILD" && ctest -N 2>/dev/null | grep -cE '^ *Test +#[0-9]+:')
  ctest_pr=$(cd "$BUILD" && ctest -N -R '^ParameterHandler' 2>/dev/null | grep -cE '^ *Test +#[0-9]+:')
  : "${listed_total:=0}" "${listed_pr:=0}" "${ctest_total:=0}" "${ctest_pr:=0}"

  (cd "$BUILD" && timeout 600 ctest --output-on-failure -R '^ParameterHandler' --output-junit "$OUT/pr-tests.xml" > "$OUT/pr-tests.txt" 2>&1)
  pr_rc=$?
  pr_counts=$(junit_ok "$OUT/pr-tests.xml"); pr_junit=$?
  pr_ran=${pr_counts%% *}
  if [ "$listed_pr" = "$EXPECTED_PR_CASES" ] && [ "$ctest_pr" = "$EXPECTED_PR_CASES" ] && [ "$pr_ran" = "$EXPECTED_PR_CASES" ] \
     && [ "$pr_rc" = 0 ] && [ "$pr_junit" = 0 ]; then
    mark pr_tests pass "$EXPECTED_PR_CASES/$EXPECTED_PR_CASES hidden cases, one process each (junit tests/failures/errors/skipped: $pr_counts)"
  else
    mark pr_tests fail "listed=$listed_pr ctest=$ctest_pr ran=$pr_ran expected=$EXPECTED_PR_CASES rc=$pr_rc junit=$pr_counts (see pr-tests.txt)"
  fi

  (cd "$BUILD" && timeout 900 ctest --output-on-failure --output-junit "$OUT/cpp-tests.xml" > "$OUT/cpp-tests.txt" 2>&1)
  all_rc=$?
  all_counts=$(junit_ok "$OUT/cpp-tests.xml"); all_junit=$?
  all_ran=${all_counts%% *}
  if [ "$listed_total" = "$EXPECTED_TOTAL_CASES" ] && [ "$ctest_total" = "$EXPECTED_TOTAL_CASES" ] && [ "$all_ran" = "$EXPECTED_TOTAL_CASES" ] \
     && [ "$all_rc" = 0 ] && [ "$all_junit" = 0 ]; then
    mark regressions pass "$EXPECTED_TOTAL_CASES/$EXPECTED_TOTAL_CASES cases, one process each (junit tests/failures/errors/skipped: $all_counts)"
  else
    mark regressions fail "listed=$listed_total ctest=$ctest_total ran=$all_ran expected=$EXPECTED_TOTAL_CASES rc=$all_rc junit=$all_counts (see cpp-tests.txt)"
  fi
else
  mark pr_tests skip; mark regressions skip
fi

# ---------------------------------------------------------------------------------------------
# 5. C crate unit tests (default features; warm dev-profile target dir).
# ---------------------------------------------------------------------------------------------
if [ "$build_ok" = 1 ]; then
  (cd "$REPO" && timeout 1500 cargo test -p foxglove_c --offline > "$OUT/cargo-test.log" 2>&1)
  ct_rc=$?
  ct_counts=$($PY - "$OUT/cargo-test.log" <<'PY'
import re, sys
passed = failed = 0
for m in re.finditer(r"test result: (\w+)\. (\d+) passed; (\d+) failed", open(sys.argv[1]).read()):
    passed += int(m.group(2)); failed += int(m.group(3))
print(passed, failed)
PY
)
  ct_passed=${ct_counts%% *}; ct_failed=${ct_counts##* }
  if [ "$ct_rc" = 0 ] && [ "${ct_failed:-1}" = 0 ] && [ "${ct_passed:-0}" -ge "$EXPECTED_MIN_C_UNIT_TESTS" ]; then
    mark c_unit_tests pass "$ct_passed passed, 0 failed (min $EXPECTED_MIN_C_UNIT_TESTS)"
  else
    mark c_unit_tests fail "rc=$ct_rc passed=$ct_passed failed=$ct_failed (min $EXPECTED_MIN_C_UNIT_TESTS; see cargo-test.log)"
  fi
else
  mark c_unit_tests skip
fi

# ---------------------------------------------------------------------------------------------
# 6. Wire-level parity against the Rust SDK reference server (and the C API driver).
# ---------------------------------------------------------------------------------------------
PARITY="$OUT/parity"
mkdir -p "$PARITY"
drivers_ok=1
if [ "$build_ok" = 1 ] && [ -n "$LIB_CPP" ] && [ -n "$LIB_C" ]; then
  if ! g++ -std=c++17 -O1 -DFOXGLOVE_REMOTE_ACCESS -DPARITY_CHECK_GATEWAY "${INC[@]}" "$TESTS/parity/cpp_driver.cpp" \
        -o "$PARITY/cpp_driver" -L"$LIBDIR_CPP" -L"$LIBDIR_C" -lfoxglove_cpp_shared -lfoxglove -lpthread \
        -Wl,-rpath,"$LIBDIR_CPP" -Wl,-rpath,"$LIBDIR_C" > "$OUT/cpp-driver-build.log" 2>&1; then
    drivers_ok=0
    mark api_validation fail "C++ parity driver failed to compile against the submitted API (see cpp-driver-build.log)"
    mark parity_cpp fail "driver did not compile"
  fi
  if ! gcc -std=gnu11 -O1 -DFOXGLOVE_REMOTE_ACCESS -DPARITY_CHECK_GATEWAY -I"$REPO/c/include" "$TESTS/parity/c_driver.c" \
        -o "$PARITY/c_driver" -L"$LIBDIR_C" -lfoxglove -lpthread -Wl,-rpath,"$LIBDIR_C" > "$OUT/c-driver-build.log" 2>&1; then
    mark parity_c fail "C parity driver failed to compile against the submitted header (see c-driver-build.log)"
    c_driver_ok=0
  else
    c_driver_ok=1
  fi
else
  drivers_ok=0; c_driver_ok=0
  mark api_validation skip; mark parity_cpp skip; mark parity_c skip
fi

if [ "$drivers_ok" = 1 ]; then
  if timeout 120 "$PARITY/cpp_driver" --check validation > "$OUT/api-validation.log" 2>&1 && grep -q VALIDATION_OK "$OUT/api-validation.log"; then
    mark api_validation pass
  else
    mark api_validation fail "half-set ParameterHandler must yield ValueError, none/both must succeed (see api-validation.log)"
  fi
  if [ ! -x "$REF" ]; then
    mark parity_cpp fail "reference server missing at $REF (verifier image problem)"
    [ "$c_driver_ok" = 1 ] && mark parity_c fail "reference server missing"
  else
    c_args=()
    [ "$c_driver_ok" = 1 ] && c_args=(--c "$PARITY/c_driver")
    timeout 900 $PY "$TESTS/parity/run_parity.py" --ref "$REF" --cpp "$PARITY/cpp_driver" "${c_args[@]}" --out "$PARITY" > "$OUT/parity.log" 2>&1
    parity_rc=$?
    summary="$PARITY/summary.json"
    if [ -f "$summary" ]; then
      read -r sanity cpp_ok c_ok <<<"$($PY - "$summary" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
sanity = "ok" if not s.get("reference_sanity") else "bad"
cpp = "ok" if s.get("cpp") and all(s["cpp"].values()) else "bad"
c = "ok" if s.get("c") and all(s["c"].values()) else ("none" if not s.get("c") else "bad")
print(sanity, cpp, c)
PY
)"
      if [ "$sanity" != ok ]; then
        mark parity_cpp fail "reference transcript failed sanity checks (verifier problem): $(tr -d '\n' < "$summary" | head -c 400)"
        [ "$c_driver_ok" = 1 ] && mark parity_c fail "reference sanity failed"
      else
        if [ "$cpp_ok" = ok ]; then mark parity_cpp pass "handler, precedence, legacy transcripts identical to the Rust SDK"; else mark parity_cpp fail "transcript mismatch vs Rust SDK (see parity/*.transcripts.json)"; fi
        if [ "$c_driver_ok" = 1 ]; then
          if [ "$c_ok" = ok ]; then mark parity_c pass "handler transcript identical to the Rust SDK"; else mark parity_c fail "C API transcript mismatch vs Rust SDK (see parity/c.transcripts.json)"; fi
        fi
      fi
    else
      mark parity_cpp fail "run_parity.py produced no summary (rc=$parity_rc, see parity.log)"
      [ "$c_driver_ok" = 1 ] && mark parity_c fail "no summary"
    fi
  fi
fi

exit 0
